### ISSUE TITLE
找不到函数名称

### ISSUE THREAD

**Issue by amesy** [liyoung1992/wechatpay#3]
在支付结果异步回调签名处 
`err = wechat_pay_recoed_producer.Publish("wechat_pay", record)`

找不到 wechat_pay_recoed_producer, 其他文件中也没有找到

**Comment by liyoung1992** [comment]
直接注释即可，是我这边忘了注释。

**Comment by selfbreak** [comment]
在回调时找不到这个函数
mv, err := mxj.NewMapXml(body)
