### ISSUE TITLE
微信回调

### ISSUE THREAD

**Issue by itcuihao** [liyoung1992/wechatpay#5]
微信回调返回
```
c.XML(http.StatusOK, gin.H{
			"return_code": "SUCCESS",
			"return_msg":  "OK",
		})
```

用postman测试结果
```
<map><return_code>SUCCESS</return_code><return_msg>OK</return_msg></map>
```
这种格式微信能识别吗？

**Comment by liyoung1992** [comment]
@itcuihao hello，微信就是要返回在这种xml格式数据。如：
![image](https://user-images.githubusercontent.com/22537644/61778060-a156e300-ae30-11e9-93fd-9fc6e421f293.png)
